"""add oauth provider

Revision ID: aa637dc9e2b1
Revises: 3a4d2b47ce13
Create Date: 2026-04-15 11:03:44.644282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa637dc9e2b1'
down_revision: Union[str, Sequence[str], None] = '3a4d2b47ce13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
